# Site settings
title:       Datasets on fee-based Open Access Publishing
email:       openapc@uni-bielefeld.de
author:      INTACT team
description: "Collecting article processing charges (APC) that German universities and research institions have paid and making them available as Open Data"
baseurl:     
url:         "https://openapc.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: "openapc"

# Social icons
show_social_icons: true
github_username: "openapc"
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true

# gem 

gems: [jekyll-paginate]